apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Values.nameSpace }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}"
    version: "{{ .Chart.Version }}"
data:
  app_id: {{ .Values.configMap.appId.value }}
  log_level: {{ .Values.configMap.logLevel.value }}
  request_limit: {{ .Values.configMap.requestLimit.value }}
  session_secret: {{ .Values.configMap.sessionSecret.value }}